# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9386c2cad111e6dc1dfec0231ccb32e32384d575a452f0f989d8079203754a4369da82bdb4a5d292ff0104c59959e90b64b93a4fb1269e4a0ff5f1c107908d3a

  secret_key_base: super_long_secret_key_for_development
  google_client_id: '670920190435-b4verhn1lr2g74sgnpl8dnbtvpk58nk6.apps.googleusercontent.com'
  #'560796484886-cvklchp0r3ieipv7l11aup7lb4e42sjv.apps.googleusercontent.com'
  google_client_secret: 'RzZC4nABIBLG6RxL4hjxyMg2'
  #'NnD3tXHtOgBTZjQRgLMRrdur'
  
test:
  secret_key_base: 6c4d61322bbc6c1db9ffe65b4b0216cc1a6e4aef60e0d313cf161825383372ef50049cee4dc5bd2d7a94350ac01289c3e4654cb9906f03cf43a91eef8325f8d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
